# Generated by Django 4.2.11 on 2024-04-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='employees', verbose_name='Снимка')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='Име и фамилия')),
                ('position', models.CharField(blank=True, default='', max_length=50, verbose_name='Длъжност')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание/резюме')),
            ],
            options={
                'verbose_name': 'Служител',
                'verbose_name_plural': 'Служители',
            },
        ),
    ]
