# Generated by Django 4.2.11 on 2024-04-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(help_text='Начален час', max_length=5, verbose_name='Час')),
            ],
            options={
                'verbose_name': 'Начален час',
                'verbose_name_plural': 'Начални часове',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Аppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('ap_name', models.CharField(max_length=60, verbose_name='Име')),
                ('ap_phone', models.CharField(max_length=14, verbose_name='Телефон')),
                ('ap_new', models.BooleanField(default=True, verbose_name='Нова резервация')),
                ('ap_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bookhour', verbose_name='Час')),
                ('ap_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Резервация',
                'verbose_name_plural': 'Резервации',
            },
        ),
    ]
