# Generated by Django 4.2.11 on 2024-04-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookhour_service_аppointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Аppointment',
            new_name='Appointment',
        ),
    ]
